"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase
"""

# approach 1: XOR
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        result = 0
        for char in s:
            result ^= ord(char) # ^ XOR ard ASCII
            print(ord(char))
        for char in t:
            result ^= ord(char)
            print(ord(char))
        print(result)
        return chr(result)

solution = Solution()
print(solution.findTheDifference("abcd", "abcde"))
print(solution.findTheDifference("", "y"))
        